# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python
      run: |
        python3 ./main.py
    - name: Move output JSON file to repository
      run: |
        mv output.json $GITHUB_WORKSPACE/output.json
      if: success()

    - name: Commit and push changes
      run: |
        git config --global user.name 'Your Name'
        git config --global user.email 'youremail@example.com'
        git add output.json
        git commit -m "Add output JSON file"
        git push
